CREATE OR REPLACE TRIGGER BRG_{code}_{attribute_table}_TRIGGER
BEFORE INSERT OR UPDATE
ON {attribute_table}
FOR EACH ROW
DECLARE
  L_PASSED      BOOLEAN := TRUE;
  V_COLUMN_1    VARCHAR2(60) := :NEW.{attribute_column};
  V_COMVALUE    VARCHAR2(255) := '{compare_with}';
  V_COMVALUE_NUM NUMBER(10);
  BEGIN

    V_COMVALUE_NUM := TO_NUMBER(V_COMVALUE);

    IF (V_COLUMN_1 {operand} V_COMVALUE_NUM) THEN
      L_PASSED := TRUE;
    ELSE
      RAISE_APPLICATION_ERROR(-20000, 'Error Raised: ' || {error});
    END IF;

EXCEPTION
  WHEN VALUE_ERROR THEN
    IF (V_COLUMN_1 {operand} V_COMVALUE) THEN
      L_PASSED := TRUE;
    ELSE
      RAISE_APPLICATION_ERROR(-20000, 'Error Raised: ' || {error});
    END IF;
  END;