CREATE OR REPLACE TRIGGER BRG_{code}_{attribute_table}_TRG
BEFORE DELETE OR INSERT OR UPDATE
ON {attribute_table}
FOR EACH ROW
DECLARE
  L_OPER        VARCHAR2(3);
  L_ERROR_STACK VARCHAR2(4000);
  L_PASSED      BOOLEAN := TRUE;
BEGIN
  IF INSERTING
  THEN
    L_OPER := 'INS';
  ELSIF UPDATING
    THEN
      L_OPER := 'UPD';
  ELSIF DELETING
    THEN
      L_OPER := 'DEL';
  END IF;
  IF L_OPER IN ('INS', 'UPD')
  THEN
    EXECUTE IMMEDIATE '{other_statement}' INTO L_PASSED;
    IF NOT l_PASSED
    THEN
      RAISE_APPLICATION_ERROR(-20000, {error});
    END IF;
  END IF;
END;